INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronicos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Sapatos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas', NOW());